# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-20 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Superstar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('fid', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=350)),
                ('keywords', models.TextField()),
            ],
        ),
    ]
